### ISSUE TITLE
Package names are different from JAM-Software/Virtual-TreeView

### ISSUE THREAD

**Issue by pyscripter** [TurboPack/VirtualTreeView#10]
I wonder whether we could use the same package naming as https://github.com/JAM-Software/Virtual-TreeView, so that users can switch between the two.

As it stands the package name differences  make it  difficult to use components that depend on VirtualTreeView such as the https://github.com/TurboPack/MustangpeakVirtualshellTools.

**Comment by pyscripter** [comment]
@jimmckeeth Any views on this?

**Comment by marcocantu** [comment]
I agree switching between the two packages looks more relevant than installing both at the same time. But I don't know the history behind this (that is, why the package names were changes when the project was forked)

**Comment by pyscripter** [comment]
@marcocantu The issue was raised before #4.  Please see @sglienke comments in favor of using the same package names.
@romankassebaum Can we do something about this?
It is also time to sync with the original repository, since there have been numerous important fixes.

**Comment by romankassebaum** [comment]
Because of historical reasons we would leave things as they are.

**Comment by pyscripter** [comment]
> Because of historical reasons we would leave things as they are.

It doesn't sound as a sufficient justification for closing the issue to me.
