### ISSUE TITLE
OnGetText event not found

### ISSUE THREAD

**Issue by steferretti** [TurboPack/VirtualTreeView#14]
Every tutorial states to use OnGetText to set the text to be painted.
Event is not there

Delphi 10.4 Community version downloaded from Getit Package Manager

**Comment by romankassebaum** [comment]
The event is definitely there

```
  TVirtualStringTree = class(TCustomVirtualStringTree)
...
  published
...
    property OnGetText;

```

**Comment by steferretti** [comment]
Please just have a look at a capture of the Object Inspector.
I can't see that event there.
Am I doing something wrong?
Best regards
Stefano
![image](https://user-images.githubusercontent.com/18648841/189493423-fcbb8d78-08f4-4927-b47f-1cc94bf80375.png)

**Comment by steferretti** [comment]
I was using VirtualDrawTree, sorry

**Comment by steferretti** [comment]
Sorry,  I was using VirtualDrawTree.
Best regards
Stefano

**Comment by steferretti** [comment]
Dear Roman,

Shouldn't it be right there, between OnGetPopupMenu and
OnGetUserClipboardFormats?
Maybe I'm doing somwthing wrong, but I just can't find it.

[image: image.png]

Best regards,
STefano

**Comment by romankassebaum** [comment]
```pascal
    property OnExpanded;
    property OnExpanding;
    property OnFocusChanged;
    property OnFocusChanging;
    property OnFreeNode;
    property OnGetCellText;
    property OnGetCellIsEmpty;
    property OnGetCursor;
    property OnGetHeaderCursor;
    property OnGetText;
    property OnPaintText;
    property OnGetHelpContext;
    property OnGetHintKind;
```
