### ISSUE TITLE
Hi, Is this the fork  VirtualTreeView 6.X for XE?

### ISSUE THREAD

**Issue by mksjgj** [TurboPack/VirtualTreeView#2]

**Comment by romankassebaum** [comment]
This is the TurboPack version. It is designed for the GetIt package manager. It allows to automatically install packages into RAD Studio.
This version always supports the latest version of RAD Studio (currently XE8).

For older Delphi versions I've created branches but currently not for XE.

I'm always interested in some help. If you have some time, compile VirtualTree with XE and I will create a branch for you. 

If you cannot do this then please send me a PM and I can send you a proposal.  My address is roman at kassebaum dot eu.
