### ISSUE TITLE
Please change the 11 and above C++ package code.

### ISSUE THREAD

**Issue by RayVecchio** [TurboPack/VirtualTreeView#20]
Hi Roman,

The Runtime Win64 (and Win32) Package code needs to be changed, to this:

```
#include <basepch.h>
#pragma hdrstop
#pragma package(smart_init)
//---------------------------------------------------------------------------

//   Package source.
//---------------------------------------------------------------------------


#pragma argsused
extern "C" int _libmain(unsigned long reason)          //rnelson added
//int WINAPI DllEntryPoint(HINSTANCE hinst, unsigned long reason, void*) //rnelson removed
{
    return 1;
}
```
The problem is that the if you use the VT in a Win64 DLL then the linker will link to the `DllEntryPoint` in the package library, causing the DLL's `DllEntryPoint` not to exported and thus not to be called.

Cheers!

Roy.

**Comment by romankassebaum** [comment]
I added your patch. I'm not a C++ specialist, so that I cannot say anything about this issue.

**Comment by RayVecchio** [comment]
Roman I have reported this bug as RS-125856.

My initial workaround will not always work if the entry point names of the DLL and Package matches you will still get the problem, what you need to do resolve it is to remove the "#pragma package(smart_init)" line from the source module that contains the entrypoint, the linker will then NOT export the entry point function as it should have done in the first place.

**Comment by romankassebaum** [comment]
Okay, I removed this line.
