### ISSUE TITLE
Please use the same package names as the original repository

### ISSUE THREAD

**Issue by sglienke** [TurboPack/VirtualTreeView#4]
You added a D to the Delphi package names which will cause conflicts when developing other components that require VirtualTrees runtime package. Please keep things compatible to each other.

**Comment by romankassebaum** [comment]
Some years ago we introduced the following pattern: DR, DD, CR and CD for Delphi, runtime, designtime and CBuilder for all packages in all libs.

Then we heard that this causes some problems in one of your libs but I thought that you already fixed the issue.
 
Anyway, I just talked to Marco and he is still thinking about what to do. At this point he would say: Ja, nein, ich meine jein. :-)

**Comment by sglienke** [comment]
Yes, I solved this issue by ignoring your name pattern and go with the name of the original repository. ;)

But this then causes problems for people using the component via GetIt as they cannot compile the package that requires VirtualTreesR.

**Comment by romankassebaum** [comment]
Please give Marco a call. He is currently uncertain.

**Comment by sglienke** [comment]
I already did

**Comment by romankassebaum** [comment]
And what did he say?

**Comment by marcocantu** [comment]
I'm a bit worried about changing the current model, already applied to several libraries and for multiple releases, but I can understand Stefan concern. I'm going to ask (internally) what others think.
