### ISSUE TITLE
10.2 tokyo install of virtualTreeView

### ISSUE THREAD

**Issue by parios59** [TurboPack/VirtualTreeView#5]
Getting error during install from getit manager.

![2017-05-29_10-32-30](https://cloud.githubusercontent.com/assets/8902122/26558591/d7ffe0de-445e-11e7-9bf3-d59bbe44e8b7.jpg)

**Comment by romankassebaum** [comment]
VirtualShellTools use VirtualTree. This means that you also have to update all the MustangPeak libs.

**Comment by parios59** [comment]
Thank You!!!!
